### PR TITLE
Rename everything from hu to ghu

### PR DESCRIPTION
**Pull request by ausbin**
One last time (ha), go through the superturboduperfun process of renaming the project and packages. We agreed on Global Humanitarians Unite, not Humanitarians United, so rename the app accordingly like we've already rename the repo and the toolkits app

### CODE REVIEW

**Comment by ausbin** [comment]
Renaming the submodule was a pain for me (I ended up having to re-clone the repo), so I'd play it safe and merge this only after you've merged whatever branches you're working on, Schuyler

**Review by S-reinken — CHANGES_REQUESTED** [review]
Need to deal with other PRs first.

**Review by S-reinken — COMMENTED** [review]
Yeah, resolve the merge conflicts, then I'll approve the PR.

**Comment by ausbin** [comment]
Alright, I rebased, but fair warning: renaming the ghu_toolkits submodule might break the hecking heck out of your local repo, or at least more than I'm qualified to fix.

So if git gets confused when you pull after we merge this, I'd just re-clone the repo (I did)

**Review by S-reinken — APPROVED** [review]
I think we'll manage.  Go ahead and merge.

**Pull request merged**
