### PR TITLE
Create ghu_global app

### PR DESCRIPTION
**Pull request by ausbin**
As Schuyler and I agreed upon, create a ghu_global app with global templates and stylesheets.

I like this approach a lot more than what I was originally thinking, in which all sites inherited templates/static files from ghu_browser (aka the main site).

### CODE REVIEW

**Review by S-reinken — CHANGES_REQUESTED** [review]
We are going to need to change this once my Pull Request is put in. Everything in hu_browser will be erased.

**Comment by ausbin** [comment]
Ah, duh, you're right

**Comment by ausbin** [comment]
Alright, there we go. Thanks for pointing that out.

This should be good now, combined with global-humanitarians-unite/ghu_main#1

**Review by S-reinken — APPROVED** [review]
Alright, let's see this Doop!

**Pull request merged**
