### PR TITLE
Goodbye, Submodules(?)

### PR DESCRIPTION
**Pull request by ausbin**
This PR sends the `ghu_web` and `ghu_toolkits` submodules to meet the good Lord. Here's my argument why I currently think we should end submodules:

1. Merely having pieces of our application in different repositories does not make our application more modular. Whether ghu_main and ghu_toolkits happen to live in separate repositories or not, they are separate Django applications, and Django [applications](https://docs.djangoproject.com/en/1.11/ref/applications/) already provide modularity.
2. Even if Point 1 was a lie, both applications depend _heavily_ on shared CSS/js/templates/models/etc. in this repository, and this repository relies on them. They're not truly independent; they are strongly coupled right now to one another (but in manageable ways imo). 
3. They're intimidating to newcomers. Understanding why you currently have to periodically run `git submodule update --remote` (because git trees store commits identified by SHA-1s and get out of date) is a burden for team members and others to get involved — something we don't want considering only Schuyler and I have worked on this so far
4. They create a lot of questions about releases: does each repository have its own version? If not, does that mean we have to keep them in sync? If so, that sounds clumsy to maintain
5. They make deployment seriously painful. Not only do they complicate the deployment scripts I'm writing in unforeseen ways; they mean you need three different SHA-1s to identify the version in prod: the commit of ghu, ghu_toolkits, and ghu_main. Worse, say I make mutually dependents changes in, say, ghu_toolkits and ghu. How do I deploy that atomically? At the very least, this complicates our deploy-on-master-push idea.  
6. It means we hand off 3 github-dependent repositories to Neil instead of 1 self-contained repository. Like I'd rather not tie our build process to github, but having github URLs in `/.gitmodules` does
7. They're just a pain in the ass in general. Seeing them every time I run `git status` is aggravating, and knowing they're always out of date bothers me 
8. I got to do a really cool 3-way merge of 3 repos with completely independent histories at 5b3af948a64506d68bfc8f719f0100fcd9a3f6b1 and it was [exciting](https://stackoverflow.com/a/31186732/321301). Yeah ok, this isn't really an argument but it's cool ok

Discussssssssssss

### CODE REVIEW

**Comment by S-reinken** [comment]
Okay.  The reason I made the project into submodules in the first place was to make it so individuals could use the TagFlow process on each one.  However, if code reviews and QAs are thorough, there shouldn't be too many conflicts having all the pull-requests for all the different pages and portions on one development tree.  Submodules are known to be outdated anyway, so I think I will approve of this.

**Review by S-reinken — APPROVED** [review]
The project will never grow large enough to warrant submodules.  I approve of deleting them.

**Comment by ausbin** [comment]
> Okay. The reason I made the project into submodules in the first place

I just wanna point out that I was 100% on board with this, so this isn't directed at you if that makes sense. Basically working on the deployment script changed my mind about submodules bc I realized it makes life harder

> was to make it so individuals could use the TagFlow process on each one.

Which I think would be worth it if they were huge codebases, y'know? Like if they _had_ (out of necessity) to act as separate projects, like as an example you gave iirc, T-Square and OSCAR. This PR is reversible — if we ever get to that point, we can split the project again.

> However, if code reviews and QAs are thorough, there shouldn't be too many conflicts having all the pull-requests for all the different pages and portions on one development tree.

If I understand what you mean, I'm thinking so too

**Review by S-reinken — COMMENTED** [review]
But make sure to solve the merge conflicts in a commit before merging this.

**Comment by ausbin** [comment]
Yeah idk what it's talking about, I thought this would be a fast-forward. I'll try and figure it out

**Comment by S-reinken** [comment]
It's actually pretty incredible how this changed the development tree. Visually it is quite interesting, and I don't think you can rebase it.

**Comment by S-reinken** [comment]
Yeah, just don't rebase it and you'll be fine. Trust me, you can't

**Comment by S-reinken** [comment]
As soon as you change the option to merge on github, it says there aren't any conflicts.

**Comment by S-reinken** [comment]
I mean, it might work, you can try, but you are merging three lines of development at once, and I do not think it is doable.

**Comment by ausbin** [comment]
I went ahead and pushed directly to master for this, I think this confused github

**Pull request merged**
